### ISSUE TITLE
Sentence-t5-xxl avg score missing

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/leaderboard#34]
Somehow the avg score for ST5-XXL is no longer displayed in the leaderboard even though the results are there in the results folder (applies to all sentence-t5 models; it seems like a few scores are missing, maybe some issue in parsing them or something)
<img width="1224" alt="Screenshot 2024-09-16 at 9 24 38 AM" src="https://github.com/user-attachments/assets/9a7aed6a-69f7-47dc-88a0-bec1a1a27069">

**Comment by Samoed** [comment]
It uses the old format, and results are expecting it to have `hf_subset` because for datasets like `AmazontCounterfactualClassification (en)`, it's necessary. This is because it's the only split of the dataset.
1. st5 results https://github.com/embeddings-benchmark/results/blob/main/results/sentence-t5-xxl/no_revision_available/AmazonCounterfactualClassification.json
2. me5 results (current format) https://github.com/embeddings-benchmark/results/blob/main/results/intfloat__e5-mistral-7b-instruct/07163b72af1488142a360786df853f237b1a3ca1/AmazonCounterfactualClassification.json

**Comment by Muennighoff** [comment]
Amazing! Do you think you could fix it?

**Comment by Samoed** [comment]
https://github.com/embeddings-benchmark/results/pull/33
