### ISSUE TITLE
update_leaderboard_daily workflow is failing

### ISSUE THREAD

**Issue by Pringled** [embeddings-benchmark/leaderboard#45]
Hi,

I noticed that the update_leaderboard_daily worfklow is failing since yesterday (e.g. https://github.com/embeddings-benchmark/leaderboard/actions/runs/11098499239/job/30831261185).

**Comment by Samoed** [comment]
@Muennighoff @orionw

**Comment by orionw** [comment]
Looks like someone added a branch rule (or GitHub’s settings changed) and it doesn’t like my permission token anymore for the commit. 

I think I should be able to resolve it with some updated permissions.  Let me try some things

**Comment by orionw** [comment]
It was a bit more complicated than I thought.  The requirements for the branch are `build`:

<img width="650" alt="image" src="https://github.com/user-attachments/assets/2e94f9b6-b350-4f81-b81f-059278a4eff9">

So to pass the branch requirements, I tried changing it to do a PR and then merge it. But when it makes a PR, it looks like this:
<img width="747" alt="image" src="https://github.com/user-attachments/assets/28c876f1-60b9-44d8-96c3-e897e7043bb3">

We don't have any "build" workflows so I am a bit confused what is actually happening. 

@KennethEnevoldsen @isaac-chung does anyone know who set this requirement and what it means? We can also do it after ICLR, I know the deadline is today.

**Comment by Pringled** [comment]
@orionw there's a "build" workflow in https://github.com/embeddings-benchmark/leaderboard/blob/main/.github/workflows/check_leaderboard_can_update.yaml, however I think it's waiting for https://github.com/embeddings-benchmark/leaderboard/actions/runs/11127222076/job/30919027011 (which was cancelled).

**Comment by Samoed** [comment]
In mteb main repo workflows are waiting too 
![image](https://github.com/user-attachments/assets/55df394e-b9db-43ef-bcdc-5c6e1e27a163)

**Comment by orionw** [comment]
> there's a "build" workflow in

Ah, thank you @Pringled, I didn't realize they could have a different name than their filename and `name` key in the workflow.

I re-started that action, but it still appears to be "waiting for status to be reported", which is weird since the PR targets the `main` branch and should activate that workflow. 

I think we're missing something that starts these (thanks for pointing that out as well @Samoed) but I'm not entirely sure why right now

**Comment by orionw** [comment]
Ah perhaps part of it is this: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

Since it tries to avoid recursive loops. That may not solve what @Samoed is referring to though.

**Comment by orionw** [comment]
Okay this is resolved, thanks @Pringled @Samoed for the help!

It turns out there were two things: (1) I changed from branch protection to a rule set that lets admins skip the branch status checks allowing it to push and (2) when I was trying to fix the first issue I changed one of the workflow’s name.  Apparently that workflow had also been named “build” and was the workflow that the branch protection was previously tied to.  I think that caused the pause in all the status checks since it was unsure what to run anymore as I deleted the reference.

**Comment by KennethEnevoldsen** [comment]
>@KennethEnevoldsen @isaac-chung does anyone know who set this requirement and what it means? We can also do it after ICLR, I know the deadline is today.

I added the requirement for "build" to pass when making PRs (this was to allow auto-merge). However I didn't know that it would influence the CI. Sounds like it is solved though otherwise let me know if I have to look more into it
